package com.example.studentlearningtracker.adapters;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;
import com.example.studentlearningtracker.R;
import com.example.studentlearningtracker.model.Student;
import java.util.List;

public class StudentAdapter extends RecyclerView.Adapter<StudentViewHolder> {

    public interface OnClick { void onStudent(Student s); }

    private final List<Student> data;
    private final OnClick cb;

    public StudentAdapter(List<Student> data, OnClick cb) {
        this.data = data; this.cb = cb;
    }

    @NonNull @Override
    public StudentViewHolder onCreateViewHolder(@NonNull ViewGroup p, int vType) { //StudentViewHolder generated by AI
        View v = LayoutInflater.from(p.getContext())
                .inflate(R.layout.row_student, p, false);
        return new StudentViewHolder(v);
    }

    @Override
    public void onBindViewHolder(@NonNull StudentViewHolder h, int pos) {
        Student s = data.get(pos);
//        System.out.println("I was here");
        h.tvRow.setText(s.id + " – " + s.examScore + "%");
        h.itemView.setOnClickListener(v -> cb.onStudent(s)); //click listener for student top 10s
    }

    @Override public int getItemCount() { return data.size(); }
}
